'use client'

import { useEffect, useState } from 'react'
import { useRouter } from 'next/navigation'

type Project = { id: string; name: string; deploy_target: string; deploy: string; uptime: string; errors: number | null; monitoring_endpoint?: string; monitoring_check_id?: string | null; sentry_project_slug?: string | null; github_owner?: string; github_repo?: string; sites?: { domain: string }[] }
function kind(value: string) { if (/not connected|unknown|no runs/i.test(value)) return 'neutral'; if (/running|pending|queued|validating/i.test(value)) return 'working'; if (/fail|error|down|cancel|past_due|unpaid/i.test(value)) return 'warning'; return 'healthy' }
function Status({ value }: { value: string }) { const state = kind(value); const icon = state === 'healthy' ? 'OK' : state === 'working' ? '...' : state === 'neutral' ? '--' : '!'; return <span className={`status ${state}`}><span aria-hidden="true">{icon}</span>{value}</span> }

export function ProjectTable({ projects, focus = 'all' }: { projects: Project[]; focus?: 'deploy' | 'monitoring' | 'all' }) {
  const router = useRouter(); const [selected, setSelected] = useState<Project | null>(null); const [index, setIndex] = useState(-1); const [editing, setEditing] = useState(false); const [message, setMessage] = useState(''); const [saving, setSaving] = useState(false)
  useEffect(() => { const onKey = (event: KeyboardEvent) => { if (!projects.length || event.metaKey || event.ctrlKey) return; if (event.key === 'ArrowDown') { event.preventDefault(); setIndex(i => Math.min(projects.length - 1, i + 1)) } else if (event.key === 'ArrowUp') { event.preventDefault(); setIndex(i => Math.max(0, i - 1)) } else if (event.key === 'Enter' && index >= 0) setSelected(projects[index]); else if (event.key === 'Escape') { setSelected(null); setEditing(false) } }; addEventListener('keydown', onKey); return () => removeEventListener('keydown', onKey) }, [projects, index])
  async function save(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault(); if (!selected) return
    setSaving(true); setMessage('')
    try {
      const values = Object.fromEntries(new FormData(event.currentTarget).entries())
      const response = await fetch(`/api/projects/${selected.id}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(values) })
      const result = await response.json().catch(() => ({}))
      if (!response.ok) return setMessage(result.error ?? `Unable to update project (${response.status}).`)
      setEditing(false); setSelected(null); router.refresh()
    } catch {
      setMessage('Could not reach the server. Check your connection and try again.')
    } finally {
      setSaving(false)
    }
  }
  const emptyCopy = focus === 'deploy' ? { icon: '⇡', title: 'No projects deployed yet', body: 'Add your first site, app, or backend to start tracking its deploys.' } : focus === 'monitoring' ? { icon: '◉', title: 'Nothing to monitor yet', body: 'Add a project with a health URL to start tracking uptime and errors.' } : { icon: 'OK', title: 'No projects yet', body: 'Add your first site, app, or backend to start monitoring it.' }
  return <>
    <div className="table-wrap"><table><thead><tr>{focus === 'deploy' ? <><th>Project</th><th>Deploy target</th><th>Last deploy</th><th>Repository</th></> : focus === 'monitoring' ? <><th>Project</th><th>Domain</th><th>Uptime</th><th>Error count</th></> : <><th>Project</th><th>Last deploy</th><th>Uptime</th><th>Error count</th></>}</tr></thead><tbody>{projects.map((project, row) => <tr key={project.id} className={row === index ? 'row-active' : ''} onClick={() => { setSelected(project); setEditing(false) }}>
      {focus === 'deploy' ? <><td><div className="project-name"><Status value={project.deploy} /><span><strong>{project.name}</strong><small>{project.sites?.[0]?.domain}</small></span></div></td><td>{project.deploy_target}</td><td><Status value={project.deploy} /></td><td><a href={`https://github.com/${project.github_owner}/${project.github_repo}`} target="_blank" rel="noreferrer" onClick={event => event.stopPropagation()}>{project.github_owner}/{project.github_repo}</a></td></> : focus === 'monitoring' ? <><td><div className="project-name"><Status value={project.uptime} /><span><strong>{project.name}</strong><small>{project.monitoring_endpoint}</small></span></div></td><td>{project.sites?.[0]?.domain}</td><td><div className="uptime-cell"><Status value={project.uptime} /><span className="history-placeholder" title="Historical uptime will appear after monitor snapshots are collected">---</span></div></td><td className={project.errors ? 'warning-number' : 'numeric'}>{project.errors ?? '--'}</td></> : <><td><div className="project-name"><Status value={project.uptime} /><span><strong>{project.name}</strong><small>{project.sites?.[0]?.domain}</small></span></div></td><td><Status value={project.deploy} /></td><td><div className="uptime-cell"><Status value={project.uptime} /><span className="history-placeholder" title="Historical uptime will appear after monitor snapshots are collected">---</span></div></td><td className={project.errors ? 'warning-number' : 'numeric'}>{project.errors ?? '--'}</td></>}
    </tr>)}{!projects.length && <tr><td colSpan={4} className="empty"><span>{emptyCopy.icon}</span><strong>{emptyCopy.title}</strong><p>{emptyCopy.body}</p></td></tr>}</tbody></table></div>
    {selected && <><aside className="detail-panel" role="dialog" aria-modal="true"><header><div><p>Project details</p><h2>{editing ? 'Quick edit' : selected.name}</h2></div><button onClick={() => { setSelected(null); setEditing(false) }} aria-label="Close details">x</button></header>{editing ? <form className="quick-edit" onSubmit={save}><label>Project name<input name="name" defaultValue={selected.name} required /></label><label>Domain<input name="domain" defaultValue={selected.sites?.[0]?.domain ?? ''} required /></label><label>Health URL<input name="monitoringEndpoint" defaultValue={selected.monitoring_endpoint ?? ''} required /></label><label>Better Uptime monitor ID<input name="monitoringCheckId" defaultValue={selected.monitoring_check_id ?? ''} /></label><label>Sentry project slug<input name="sentryProjectSlug" defaultValue={selected.sentry_project_slug ?? ''} /></label>{message && <p className="quick-edit-error">{message}</p>}<div><button type="button" onClick={() => setEditing(false)}>Cancel</button><button type="submit" disabled={saving}>{saving ? 'Saving...' : 'Save changes'}</button></div></form> : <><section><span>Domain</span><strong>{selected.sites?.[0]?.domain ?? 'Not set'}</strong></section><section><span>Deployment target</span><strong>{selected.deploy_target}</strong></section><section><span>Latest deploy</span><Status value={selected.deploy} /></section><section><span>Uptime</span><Status value={selected.uptime} /></section><section><span>Active errors</span><strong className={selected.errors ? 'warning-number' : ''}>{selected.errors ?? 0}</strong></section><button className="quick-edit-button" onClick={() => setEditing(true)}>Quick edit</button><p className="detail-note">Deploy history and monitor charts will appear here as monitoring snapshots accumulate.</p></>}</aside><button className="detail-backdrop" onClick={() => { setSelected(null); setEditing(false) }} aria-label="Close project details" /></>}
  </>
}
